import "@design-system/globals.css";

import { cn } from "@design-system/utils";
import type { Metadata } from "next";
import { ReactNode } from "react";

import { fonts } from "../lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex min-h-screen flex-col bg-background font-sans antialiased",
          fonts.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
};
